wip

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -58,15 +58,20 @@ runs:
         aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
         aws-region: ${{ inputs.region }}
 
-    - name: Load keystore secrets
-      if: steps.secrets-cache.outputs.cache-hit != 'true'
+    - name: Load keystore secrets from AWS
       shell: bash
       run: |
-        echo "Fetching keystore secrets from Secrets Manager..."
-        echo "KEYSTORE_BASE64=$(aws secretsmanager get-secret-value --secret-id keystore-p12-base64 --query SecretString --output text)" >> $GITHUB_ENV
-        echo "KEYSTORE_PASSWORD_BASE64=$(aws secretsmanager get-secret-value --secret-id keystore-pwd-base64 --query SecretString --output text)" >> $GITHUB_ENV
-        echo "DEFAULT_AUTH_JWT=true" >> $GITHUB_ENV # use jwt validation for authenticated routes
-        echo "Secrets fetched and exported to environment."
+        echo "Fetching keystore secrets..."
+        KEYSTORE_BASE64=$(aws secretsmanager get-secret-value --secret-id keystore-p12-base64 --query SecretString --output text | sed 's/[\r\n]//g')
+        KEYSTORE_PASSWORD_BASE64=$(aws secretsmanager get-secret-value --secret-id keystore-pwd-base64 --query SecretString --output text | sed 's/[\r\n]//g')
+        if [[ -z "$KEYSTORE_BASE64" || -z "$KEYSTORE_PASSWORD_BASE64" ]]; then
+          echo "❌ Failed to fetch secrets."
+          exit 1
+        fi
+        echo "KEYSTORE_BASE64=$KEYSTORE_BASE64" >> $GITHUB_ENV
+        echo "KEYSTORE_PASSWORD_BASE64=$KEYSTORE_PASSWORD_BASE64" >> $GITHUB_ENV
+
+        echo "✅ Secrets sanitized and exported successfully."
 
     - name: Clean, compile, and run tests
       shell: bash
